----LAB-CYCLE-1----
select scost from software where dev_d='Pascal';
select pname,floor((sysdate-dob)/365) as age from programmer;
select pname from studies where course like '%DAP%';
select title from software where sold=(select max(sold)from software);
select pname,dob from programmer where substr(dob,4,2)='01';
select course,cost from studies where cost=(select min(cost) from studies);
--select min(cost) from studies;
select count(*) from studies where course like '%PGDCA%';
select sum(scost*sold) from software where dev_d='C';
select * from software where pname='Ramesh';
select count(*) from studies where splace='Sabhari';
select * from software where (scost*sold)>2000;
select title,ceil(dcost/scost) as "Min Copies to be sold" from software;
select * from software where dcost<=(scost*sold);
select scost from software where dev_d='Basic' and scost=(select max(scost) from software where dev_d='Basic');
select count(*) from software where dev_d='Dbase';
select count(*) from studies where splace='Pragathi';
select count(*) from studies where cost between 5000 and 10000;
select ceil(avg(cost)) from studies;
select * from programmer where prof1='C' or prof2='C';
select count(*) from programmer where prof1 in('Cobol','Pascal') or prof2 in('Cobol','Pascal');
--where prof1='Cobol' or prof2='Pascal' or prof2='Cobol' or prof1='Pascal';
select count(*) from programmer where prof1 not in('C','Pascal') and prof2 not in('C','Pascal');
--where (prof1!='C' and prof1!='Pascal') and (prof2!='Pascal' and prof2!='C');
select floor(max((sysdate-dob)/365)) as "Age of oldest programmer"  from programmer where gender='M';
select avg((sysdate-dob)/365) avg_age from programmer where gender='F';
select pname,floor((sysdate-doj)/365) as experience from programmer order by pname desc;
select pname from programmer where substr(dob,4,2)=substr(sysdate,4,2);
select distinct(prof1) as languages from programmer where gender='M' union select distinct(prof2) as languages from programmer where gender='M';
select avg(salary) avg_salary from programmer;
select count(*) from programmer where gender='M';
select count(*) from programmer where salary between 2000 and 4000;
select * from programmer where prof1 not in ('Fortran','Cobol','Pascal') and prof2 not in ('Fortran','Cobol','Pascal');
--where prof1!='Cobol' and prof1!='Fortran' and prof1!='Pascal' and prof2!='Pascal' and prof2!='Cobol' and prof2!='Fortran';
select to_char(doj,'month') as most_programmers_joined_in from programmer group by to_char(doj,'month') having count(*) =(select max(count(*)) from programmer group by to_char(doj,'month'));
select prof1 proficient_language,count(*) from (select prof1 from programmer union all select prof2 from programmer) group by prof1 having count(*) =(select max(count(*)) from (select prof1 from programmer union all select prof2 from programmer) group by prof1);
select pname from programmer where gender='F' and salary>(select max(salary) from programmer where gender='M');
select prof1 from programmer group by prof1 having count(*)=(select max(count(*)) from programmer group by prof1);
--35